# Un "YAML Anchor" (&) define un bloque de configuracion para evitar duplicar codigo.
# En este archivo, se hace una sola la configuracion base de Airflow (imagen, variables, volumenes).
# Con la inyeccion (<<: *), este bloque se hereda en los
# servicios de init, webserver y scheduler. Esto hace que todos los nodos del
# orquestador compartan el mismo estado y configuracion.
x-airflow-common: &airflow-common
  build:
    context: ./airflow
  image: p2-airflow:2.10.5-python3.11
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
    PYTHONPATH: /opt/airflow/dags
    # Necesario para que el contenedor de Airflow pueda hablar con el daemon
    # de Docker del HOST y lanzar/controlar los otros contenedores via DockerOperator
    AIRFLOW_CONN_DOCKER_DEFAULT: "docker://"
    # Variables de entorno por si las usan dentro de los DAGs
    SPARK_MASTER_URL: spark://spark-master:7077
    MONGO_URI: mongodb://mongo:27017
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./:/opt/airflow/project
    - ./loader:/opt/airflow/dags/loader
    - ./raw:/opt/airflow/raw
    # Monta el socket de Docker del host para que DockerOperator pueda
    # levantar/controlar contenedores hermanos (Loader, Transformer, etc)
    - /var/run/docker.sock:/var/run/docker.sock
  user: "${AIRFLOW_UID:-50000}:0"
  group_add:
    - "${DOCKER_GID:-999}"
  depends_on:
    airflow-postgres:
      condition: service_healthy
 


services:
  spark-master:
    build:
      context: ./spark
    image: p2-spark:4.1.2-scala2.13-java17-python3-r-ubuntu
    container_name: spark-master
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "9090:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./data:/opt/spark-data:ro
      - ./spark/jobs:/opt/spark-jobs:ro
    networks:
      - spark-net

  spark-worker-1:
    build:
      context: ./spark
    image: p2-spark:4.1.2-scala2.13-java17-python3-r-ubuntu
    container_name: spark-worker-1
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    volumes:
      - ./data:/opt/spark-data:ro
      - ./spark/jobs:/opt/spark-jobs:ro
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-2:
    build:
      context: ./spark
    image: p2-spark:4.1.2-scala2.13-java17-python3-r-ubuntu
    container_name: spark-worker-2
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    volumes:
      - ./data:/opt/spark-data:ro
      - ./spark/jobs:/opt/spark-jobs:ro
    depends_on:
      - spark-master
    networks:
      - spark-net
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    networks:
      - spark-net
 
  airflow-postgres:
    image: postgres:16
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
 
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true
    restart: "no"
 
  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      airflow-init:
        condition: service_completed_successfully
 
  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
 

networks:
  spark-net:
    name: spark-net
    driver: bridge
volumes:
  mongo-data:
  airflow-postgres-data:
