services:
  spark-master:
    image: apache/spark:4.1.2-scala2.13-java17-python3-r-ubuntu
    container_name: spark-master
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./data:/opt/spark-data:ro
      - ./spark/jobs:/opt/spark-jobs:ro
    networks:
      - spark-net

  spark-worker-1:
    image: apache/spark:4.1.2-scala2.13-java17-python3-r-ubuntu
    container_name: spark-worker-1
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    volumes:
      - ./data:/opt/spark-data:ro
      - ./spark/jobs:/opt/spark-jobs:ro
    depends_on:
      - spark-master
    networks:
      - spark-net

  spark-worker-2:
    image: apache/spark:4.1.2-scala2.13-java17-python3-r-ubuntu
    container_name: spark-worker-2
    entrypoint: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_CORES=1
    volumes:
      - ./data:/opt/spark-data:ro
      - ./spark/jobs:/opt/spark-jobs:ro
    depends_on:
      - spark-master
    networks:
      - spark-net
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db
    networks:
      - spark-net

networks:
  spark-net:
    name: spark-net
    driver: bridge
volumes:
  mongo-data:
